name: WatchNext
options:
  bundleIdPrefix: com.madzine
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 14
    MARKETING_VERSION: 1.5.1
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: W89J6VDBML

targets:
  WatchNext:
    type: application
    platform: macOS
    sources:
      - path: WatchNext
        excludes:
          - "**/.DS_Store"
    info:
      path: WatchNext/Info.plist
      properties:
        CFBundleIconFile: AppIcon.icns
    entitlements:
      path: WatchNext/WatchNext.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.madzine.WatchNext
        INFOPLIST_KEY_CFBundleDisplayName: "WatchNext"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.entertainment"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ENTITLEMENTS: WatchNext/WatchNext.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: WatchNext/WatchNext-Bridging-Header.h
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_REQUIRED: NO

  WatchNext-iOS:
    type: application
    platform: iOS
    sources:
      - path: WatchNext
        excludes:
          - "**/.DS_Store"
    entitlements:
      path: WatchNext/WatchNext-iOS.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.madzine.WatchNext
        INFOPLIST_KEY_CFBundleDisplayName: "WatchNext"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.entertainment"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        SWIFT_OBJC_BRIDGING_HEADER: WatchNext/WatchNext-Bridging-Header.h
        CODE_SIGN_ENTITLEMENTS: WatchNext/WatchNext-iOS.entitlements
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_REQUIRED: NO
